### PR TITLE
fix: Improved package.json resolution logic

### LINKED ISSUE #671: IO error occurs if package.json resolution results in a directory
While verifying #670, I found different issues.

```javascript
// reproduction.js
const a = require('pg');
```
```
% llrt reproduction.js
Error: IO Error: Is a directory (os error 21)
  at <anonymous> (/Users/shinya/Workspaces/llrt-test/reproduction.js:1:11)
```

I checked the package.json of the `pg` module and found a consideration leak.

package.json:
```json
{
  "main": "./lib",
}
```

In the case of such a description, we had to refer to `index.js` directly under that directory.

### PR DESCRIPTION
**Pull request by nabetti1720**
### Issue # (if available)

Fixed #671

### Description of changes

- Fix package.json so that “index” is used as the name of the file directly under it when the resolved result is a directory.

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: llrt_core/src/module_loader/resolver.rs [hunk 1]
```diff
@@ -614,8 +614,11 @@ fn correct_extensions<'a>(x: String) -> Cow<'a, str> {
     if Path::new(&x).is_file() {
         return x.into();
     }
+
+    let index = if Path::new(&x).is_dir() { "/index" } else { "" };
+
```
Comment (richarddavison) [inline llrt_core/src/module_loader/resolver.rs:619]: Create Path once and pull in metadata. is_dir and is_file each call metadata which adds extra cost. Better to reuse metadata and match on metadata.is_dir/is_file.

**Review by richarddavison — CHANGES_REQUESTED** [review]

**Review by richarddavison — APPROVED** [review]
