### PR TITLE
fix(module): Correctly handle 'require' with parent directory specification

### LINKED ISSUE #1245: A request that specifies only the parent directory will fail
The following code is in the module `aws-embedded-metrics`:

```javascript
// aws-embedded-metrics/lib/logger/MetricsLoggerFactory.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.createMetricsLogger = void 0;
const __1 = require("..");
const EnvironmentDetector_1 = require("../environment/EnvironmentDetector");
const MetricsContext_1 = require("./MetricsContext");
const createMetricsLogger = () => {
    const context = MetricsContext_1.MetricsContext.empty();
    return new __1.MetricsLogger(EnvironmentDetector_1.resolveEnvironment, context);
};
exports.createMetricsLogger = createMetricsLogger;
```

The current package resolver cannot resolve `require("..")`. Normally, when specified like this, it would need to look for `index.js` or similar in the parent directory.

### PR DESCRIPTION
**Pull request by nabetti1720**
### Issue # (if available)

Fixed #1245 

### Description of changes

When a command is specified as `require("..")`, it now searches for the specified file in the parent directory.

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: llrt_modules/src/package/resolver.rs [hunk 1]
```diff
@@ -144,7 +144,7 @@ pub fn require_resolve<'a>(
 
     let x_is_absolute = path::is_absolute(x);
     let x_starts_with_current_dir = x.starts_with("./");
-    let x_starts_with_parent_dir = x.starts_with("../");
+    let x_starts_with_parent_dir = x.starts_with("..");
```
Comment (richarddavison) [inline llrt_modules/src/package/resolver.rs:147]: Ahhh sneaky one! Thanks for spotting!

**Review by richarddavison — APPROVED** [review]
Fantastic!!!!

**Review by richarddavison — APPROVED** [review]
