### PR TITLE
fix #840: resolve supports paths starting with ..

### LINKED ISSUE #840: Can't run file in the parent directory
```
➜ LLRT_LOG=trace ./llrt ../x.js
2025-02-14T17:34:25.536Z TRACE llrt: Started runtime
2025-02-14T17:34:25.539Z TRACE llrt: Initialized VM in 3ms
2025-02-14T17:34:25.539Z TRACE llrt_core::module_loader::resolver: Try resolve '../x.js' from 'eval_script'
2025-02-14T17:34:25.539Z TRACE llrt_core::module_loader::resolver: require_resolve(x, y):(../x.js, eval_script)
2025-02-14T17:34:25.539Z TRACE llrt_core::module_loader::resolver: +- Resolved by `FILE`: ../x.js

2025-02-14T17:34:25.539Z TRACE llrt_core::module_loader::loader: Loading module: /Users/xxx/develop/llrt/target/debug/x.js
Error: IO Error: No such file or directory (os error 2)
```

```
➜ ls ..
CACHEDIR.TAG  debug  tmp  x.js
```
Seems there's a issue in the `join_resolve_path` function.

### PR DESCRIPTION
**Pull request by ahaoboy**
### Issue # (if available)

close: https://github.com/awslabs/llrt/issues/840

### Checklist

- [ ] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [ ] Ran `make fix` to format JS and apply Clippy auto fixes
- [ ] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: modules/llrt_path/src/lib.rs [hunk 1]
```diff
@@ -434,16 +439,24 @@ where
...
                 ".." => {
-                    empty = false;
                     if let Some(last_index) = index_stack.pop() {
                         result.truncate(last_index);
+                        // maybe don't need this?
+                        // empty = false;
+                    } else if empty {
+                        if let Some(last_index) = find_last_sep(&result) {
+                            result.truncate(last_index);
+                        }
```
Comment (richarddavison) [inline modules/llrt_path/src/lib.rs:449]: No we don't need empty. There is also still an empty further down. Please remove and we should be good to go :)

**Review by richarddavison — CHANGES_REQUESTED** [review]
Sorry for the delay. Minor comment and we should be good to go!

**Review by richarddavison — APPROVED** [review]
Thanks, LGTM!
