### PR TITLE
fix: throwing exceptions during module initialization

### LINKED ISSUE #482: Exceptions thrown during module initialization are not caught
Exceptions thrown during the initialization of a global or module are not caught. This means exceptions thrown at this point will be missing the exception message.

How to replicate
---------
Running this
```
LLRT_NET_DENY=/ ./llrt -e 'console.log("123")'
```
Outputs
```
Error: Exception
```
But it should output
```
ReferenceError: LLRT_NET_DENY env contains an invalid URI
```

How to fix
----------
This is where the exceptions should probably be caught:
https://github.com/awslabs/llrt/blob/9e21153db5b7c6a3107462e97989b3c6a0e868c4/llrt_core/src/vm.rs#L426

Example of catching an exception: https://github.com/awslabs/llrt/blob/9e21153db5b7c6a3107462e97989b3c6a0e868c4/llrt_core/src/vm.rs#L448

### PR DESCRIPTION
**Pull request by nabetti1720**
### Issue # (if available)

Fixed #482 

### Description of changes

This PR will allow the correct output of the content of errors during module initialization.

After the revision:
```shell
% LLRT_NET_DENY=/ ./llrt -e 'console.log("123")'
ReferenceError: LLRT_NET_DENY env contains an invalid URI
```

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: llrt_core/src/vm.rs [hunk 1]
```diff
@@ -423,10 +423,16 @@ impl Vm {
         let ctx = AsyncContext::full(&runtime).await?;
         ctx.with(|ctx| {
             for init_global in init_globals {
-                init_global(&ctx)?;
+                if let Err(err) = init_global(&ctx).catch(&ctx) {
```
Comment (richarddavison) [inline llrt_core/src/vm.rs:426]: Since we’re handling the error the same way we can put everything in a closure and handle the error once:

```rust
({
//all init code
}).catch()…
```

**Review by richarddavison — CHANGES_REQUESTED** [review]
Thanks for the fix! I think we can merge all error handling for init!

File: llrt_core/src/vm.rs (hunk 1 above)
Comment (nabetti1720) [reply llrt_core/src/vm.rs:426]: Thanks for pointing that out. It was a little confusing, but there was a similar implementation, so we modified it based on the following. :)

https://github.com/awslabs/llrt/blob/9824e4163fb8cf103066d7b5938929740304a4ff/llrt_core/src/compiler.rs#L65-L66

**Review by richarddavison — APPROVED** [review]
