### PR TITLE
fix(utils): remove expect from ObjectBytes

### LINKED ISSUE #700: ObjectByres should not expect on detached buffer
Whoever has time, we need to make the `as_bytes` function return a result and fix all the places where it it called.

### PR DESCRIPTION
**Pull request by nabetti1720**
### Issue # (if available)

Closed #700

### Description of changes

This PR removes the `expect` instruction used in ObjectBytes's `as_bytes()` and allows it to return `std::result::Result` or `rquickjs::Result` types.

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: modules/llrt_crypto/src/lib.rs [hunk 1]
```diff
@@ -246,8 +246,8 @@ impl ModuleDef for CryptoModule {
                 let class_name: &str = sha_algorithm.class_name();
                 let algo = sha_algorithm;
 
-                let ctor = Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |secret| {
-                    ShaHash::new(algo.clone(), secret)
+                let ctor = Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move || {
```
Comment (Sytten) [inline modules/llrt_crypto/src/lib.rs:249]: Need an explanation here this is weird and not related to the pr

File: modules/llrt_crypto/src/sha_hash.rs [hunk 2]
```diff
@@ -195,8 +197,15 @@ pub struct ShaHash {
...
-        let secret = secret.0.map(|bytes| bytes.into_bytes());
+    pub fn new<'js>(
+        ctx: &Ctx<'js>,
+        algorithm: ShaAlgorithm,
+        secret: Opt<ObjectBytes<'js>>,
+    ) -> Result<Self> {
+        let secret = secret
+            .0
+            .map(|bytes| bytes.into_bytes(ctx))
+            .and_then(|res| res.ok());
```
Comment (Sytten) [inline modules/llrt_crypto/src/sha_hash.rs:208]: That is effectively silencing the error which is likely not what we want use transpose instead and return the error

File: modules/llrt_crypto/src/subtle/encryption_algorithm.rs [hunk 3]
```diff
@@ -78,7 +78,9 @@ impl<'js> FromJs<'js> for EncryptionAlgorithm {
 
                 let additional_data = obj
                     .get_optional::<_, ObjectBytes>("additionalData")?
-                    .map(|v| v.into_bytes().into_boxed_slice());
+                    .map(|v| v.into_bytes(ctx))
+                    .and_then(|res| res.ok())
```
Comment (Sytten) [inline modules/llrt_crypto/src/subtle/encryption_algorithm.rs:82]: Same here

File: modules/llrt_crypto/src/subtle/encryption_algorithm.rs [hunk 4]
```diff
@@ -99,7 +101,10 @@ impl<'js> FromJs<'js> for EncryptionAlgorithm {
             "RSA-OAEP" => {
                 let label = obj
                     .get_optional::<_, ObjectBytes>("label")?
-                    .map(|bytes| bytes.into_bytes().into_boxed_slice());
+                    .map(|bytes| bytes.into_bytes(ctx))
+                    .and_then(|res| res.ok())
```
Comment (Sytten) [inline modules/llrt_crypto/src/subtle/encryption_algorithm.rs:105]: And here

**Review by Sytten — CHANGES_REQUESTED** [review]

File: modules/llrt_crypto/src/lib.rs (hunk 1 above)
Comment (nabetti1720) [reply modules/llrt_crypto/src/lib.rs:249]: `ShaHash::new()` calls `ObjectBytes::into_bytes()`, but because this function requires `ctx` as an argument, it was also necessary to add `ctx` to the arguments of `ShaHash::new()`.

Doing so caused a lifetime problem, which I was unable to resolve, so I prepared the simpler `ShaHash::default()`.

image

Comment (nabetti1720) [reply modules/llrt_crypto/src/lib.rs:249]: image

Looks like we've made some progress. Is this error telling us that `ShaHash` needs to implement the `IntoJs` trait?

Comment (Sytten) [reply modules/llrt_crypto/src/lib.rs:249]: It is just that it changes the constructor definition that was my concern. We should be able to get the context from somewhere.

Comment (nabetti1720) [reply modules/llrt_crypto/src/lib.rs:249]: The lifetime issue occurred because the closure parameters did not include `ctx`.
However, I still get the following error:

```rust
                let ctor =
                    Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |ctx, secret| {
                        ShaHash::new(ctx, algo.clone(), secret)
                    })?;
```
```
error[E0277]: the trait bound `{closure@modules/llrt_crypto/src/lib.rs:254:74: 254:92}: IntoJsFunc<'_, _>` is not satisfied
   --> modules/llrt_crypto/src/lib.rs:254:55
    |
254 |                     Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |ctx, secret| {
    |                                                       ^ the trait `IntoJsFunc<'_, _>` is not implemented for closure `{closure@modules/llrt_crypto/src/lib.rs:254:74: 254:92}`
    |
    = help: the following other types implement trait `IntoJsFunc<'js, P>`:
              `MutFn<Fun>` implements `IntoJsFunc<'js, ()>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F, G)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F, G, H)>`
            and 41 others
note: required by a bound in `rquickjs::function::Constructor::<'js>::new_class`
   --> /Users/shinya/.cargo/git/checkouts/rquickjs-c5d9b5f474075f2d/6a60607/core/src/value/function.rs:199:12
    |
197 |     pub fn new_class<C, F, P>(ctx: Ctx<'js>, f: F) -> Result<Self>
    |            --------- required by a bound in this associated function
198 |     where
199 |         F: IntoJsFunc<'js, P> + 'js,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Constructor::<'js>::new_class`
```

At least at this point, I don't need to specify a secret variable for `ShaHash`, so I think a simple constructor like `ShaHash::default()` would be sufficient, right?

Comment (nabetti1720) [reply modules/llrt_crypto/src/lib.rs:249]: Sorry, I understand why you didn't get the context.
But I'm still getting the error...

```rust
                let ctor =
                    Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |ctx, secret| {
                        ShaHash::new(ctx, algo.clone(), secret)
                    })?;
```
```
error[E0277]: the trait bound `{closure@modules/llrt_crypto/src/lib.rs:250:74: 250:92}: IntoJsFunc<'_, _>` is not satisfied
   --> modules/llrt_crypto/src/lib.rs:250:55
    |
250 |                     Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |ctx, secret| {
    |                                                       ^ the trait `IntoJsFunc<'_, _>` is not implemented for closure `{closure@modules/llrt_crypto/src/lib.rs:250:74: 250:92}`
    |
    = help: the following other types implement trait `IntoJsFunc<'js, P>`:
              `MutFn<Fun>` implements `IntoJsFunc<'js, ()>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F, G)>`
              `MutFn<Fun>` implements `IntoJsFunc<'js, (A, B, C, D, E, F, G, H)>`
            and 41 others
note: required by a bound in `rquickjs::function::Constructor::<'js>::new_class`
   --> /Users/shinya/.cargo/git/checkouts/rquickjs-c5d9b5f474075f2d/6a60607/core/src/value/function.rs:199:12
    |
197 |     pub fn new_class<C, F, P>(ctx: Ctx<'js>, f: F) -> Result<Self>
    |            --------- required by a bound in this associated function
198 |     where
199 |         F: IntoJsFunc<'js, P> + 'js,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Constructor::<'js>::new_class`
 ```

Comment (Sytten) [reply modules/llrt_crypto/src/lib.rs:249]: I think from what I remember you do have to use a tuple for parameters of a js function.
I will have to check the code I dont really have all the context here to understand if we need the secret parameter or not in the ctr.

Comment (richarddavison) [reply modules/llrt_crypto/src/lib.rs:249]: Yeah this changes the constructor. I suspect this is a lifetime issue.
Try with something like this:
```rust
 let ctor =
                    Constructor::new_class::<ShaHash, _, _>(ctx.clone(), move |ctx, secret| {
                        struct Args<'js>(Ctx<'js>,Opt<ObjectBytes<'js>>);
                        let Args(ctx,secret) = Args(ctx,secret);
                        ShaHash::new(ctx, algo.clone(), secret)
                    })?;
```

**Review by richarddavison — CHANGES_REQUESTED** [review]
Thanks, just a minor comment regarding object bytes

**Comment by nabetti1720** [comment]
Thanks @Sytten and @richarddavison. I think I've responded to all the reviews.

**Review by richarddavison — APPROVED** [review]
